version: "3.1"
services: 
  db: 
    build:
      context: './database'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - nodemon.json
    ports:
      - "3306:3306"
  api: 
    build: './'
    command: nodemon start
    restart: always
    env_file:
      - nodemon.json
    depends_on:
      - db
    ports:
      - "3000:3000"